" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!
set t_Co=256
set background=dark
set autoindent
filetype indent on
set shiftwidth=2
set tabstop=2
set nopaste
set pastetoggle=<F2>
map <F5> :setlocal spell! spelllang=en_us<CR>
syntax on
colo kolor

"http://stackoverflow.com/questions/4998582/show-whitespace-characters-in-gvim
map <F4> :set list!<CR>
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
highlight SpecialKey term=standout ctermbg=yellow guibg=yellow
highlight RedundantSpaces term=standout ctermbg=Grey guibg=#ffddcc

set showmatch     " show matching brackets (),{},[]
set mat=5         " show matching brackets for 0.5 seconds

" Common groups that link to default highlighting.
" You can specify other highlighting easily.
hi link String  Constant
hi link Character Constant
hi link Number  Constant
hi link Boolean Constant
hi link Float   Number
hi link Conditional Statement
hi link Label   Statement
hi link Keyword Statement
hi link Exception Statement
hi link Include PreProc
hi link Define  PreProc
hi link Macro   PreProc
hi link PreCondit PreProc
hi link StorageClass  Type
hi link Structure Type
hi link Typedef Type
hi link Tag   Special
hi link SpecialChar Special
hi link Delimiter Special
hi link SpecialComment Special
hi link Debug   Special

let g:kolor_italic=1                    " Enable italic. Default: 1
let g:kolor_bold=1                      " Enable bold. Default: 1
let g:kolor_underlined=0                " Enable underline. Default: 0
let g:kolor_alternative_matchparen=0    " Gray 'MatchParen' color. Default: 0
