#!/bin/bash

mp=/mnt		# mount point of root - edit to your system
mpb=/mnt/boot	# mount point of boot - edit to your system (optional)
boot=/dev/sda2	# edit to your system
root=/dev/sda3	# edit to your system

mount $root $mp
mount $boot $mpb

cd $mp
rm console ; mknod -m 600 console c 5 1
rm null ; mknod -m 666 null c 1 3
rm zero ; mknod -m 666 zero c 1 5

mount -t proc proc $mp/proc
mount -t sysfs sys $mp/sys
mount -o bind /dev $mp/dev
echo "If installing grub or grub2 in the chroot, execute the following command:"
echo "grep -v rootfs /proc/mounts > /etc/mtab"

chroot $mp /bin/bash

#umount $mpb
#umount $mp/{proc,sys,dev}
#umount $mp
